name = "calendarhub-worker"
workers_dev = true
preview_urls = true
compatibility_date = "2026-07-21"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

[triggers]
crons = ["7 * * * *"]

[[routes]]
pattern = "calendarhub.mou7s.com"
zone_name = "mou7s.com"
custom_domain = true

[[kv_namespaces]]
binding = "SPACEX_KV"
id = "1418127f36b744c282be41d017be1620"
preview_id = "74360fe4396b4a7ba0a69a6f4888fa20"

[[kv_namespaces]]
binding = "KV"
id = "1418127f36b744c282be41d017be1620"
